apiVersion: v2
name: oasis
version: 0.1.1
type: application
description: Deploys the Oasis Platform

appVersion: "1.26.2"
home: https://github.com/OasisLMF

dependencies:
  - name: ingress-nginx
    version: "4.0.6"
    repository: https://kubernetes.github.io/ingress-nginx

maintainers:
  - name: slashme101
    email: slashme101@yahoo.com
